lichess_homepage:
    pattern:        /:color
    defaults:       { _controller: LichessBundle:Main:index, color: white }
    requirements:   { color: (white|black) }
lichess_sync:
    pattern:        /sync/:id/:color/:version/:playerFullId
    defaults:       { _controller: LichessBundle:Player:sync, playerFullId "" }
    requirements:   { id: "[\w\-]{8}", color: (white|black), version: "\d+", playerFullId "([\w\-]{12}|)" }
lichess_move:
    pattern:        /move/:id/:version
    defaults:       { _controller: LichessBundle:Player:move }
    requirements:   { id: "[\w\-]{12}", version: "\d+" }
lichess_say:
    pattern:        /talk/:id/:version
    defaults:       { _controller: LichessBundle:Player:say }
    requirements:   { id: "[\w\-]{12}", version: "\d+" }
lichess_invite_friend:
    pattern:        /friend/:color
    defaults:       { _controller: LichessBundle:Game:inviteFriend, color: white }
    requirements:   { color: (white|black) }
lichess_wait_friend:
    pattern:        /friend/:id
    defaults:       { _controller: LichessBundle:Player:waitFriend }
    requirements:   { id: "[\w\-]{12}" }
lichess_game:
    pattern:        /:id
    defaults:       { _controller: LichessBundle:Game:show }
    requirements:   { id: "[\w\-]{8}" }
lichess_player:
    pattern:        /:id
    defaults:       { _controller: LichessBundle:Player:show }
    requirements:   { id: "[\w\-]{12}" }
lichess_invite_ai:
    pattern:        /ai/:color
    defaults:       { _controller: LichessBundle:Game:inviteAi, color: white }
    requirements:   { color: (white|black) }
lichess_join_game:
    pattern:        /join/:id
    defaults:       { _controller: LichessBundle:Game:join }
    requirements:   { id: "[\w\-]{8}" }
lichess_invite_anybody:
    pattern:        /anybody/:color
    defaults:       { _controller: LichessBundle:Game:inviteAnybody, color: white }
    requirements:   { color: (white|black) }
lichess_wait_anybody:
    pattern:        /anybody/:id
    defaults:       { _controller: LichessBundle:Player:waitAnybody }
    requirements:   { id: "[\w\-]{12}" }
lichess_resign:
    pattern:        /resign/:id
    defaults:       { _controller: LichessBundle:Player:resign }
    requirements:   { id: "[\w\-]{12}" }
lichess_outoftime:
    pattern:        /outoftime/:id/:version
    defaults:       { _controller: LichessBundle:Player:outoftime }
    requirements:   { id: "[\w\-]{12}", version: "\d+" }
lichess_table:
    pattern:        /table/:id/:color/:playerFullId
    defaults:       { _controller: LichessBundle:Player:table, playerFullId "" }
    requirements:   { id: "[\w\-]{8}", color: (white|black), playerFullId "([\w\-]{12}|)" }
lichess_opponent:
    pattern:        /opponent/:id/:color/:playerFullId
    defaults:       { _controller: LichessBundle:Player:opponent, playerFullId "" }
    requirements:   { id: "[\w\-]{8}", color: (white|black), playerFullId "([\w\-]{12}|)" }
lichess_ai_level:
    pattern:        /level/:id
    defaults:       { _controller: LichessBundle:Player:aiLevel }
    requirements:   { id: "[\w\-]{12}" }
lichess_list_current:
    pattern:        /games
    defaults:       { _controller: LichessBundle:Game:listCurrent }
lichess_list_current_inner:
    pattern:        /games-refresh/:ids
    defaults:       { _controller: LichessBundle:Game:listCurrentInner }
lichess_list_all:
    pattern:        /games/all
    defaults:       { _controller: LichessBundle:Game:listAll }
lichess_list_mates:
    pattern:        /games/checkmate
    defaults:       { _controller: LichessBundle:Game:listCheckmate }
lichess_about:
    pattern:        /about
    defaults:       { _controller: LichessBundle:Main:about }
lichess_rematch:
    pattern:        /rematch/:id
    defaults:       { _controller: LichessBundle:Player:rematch }
    requirements:   { id: "[\w\-]{12}" }
lichess_force_resignation:
    pattern:        /force-resign/:id
    defaults:       { _controller: LichessBundle:Player:forceResign }
    requirements:   { id: "[\w\-]{12}" }
lichess_claim_draw:
    pattern:        /claim-draw/:id
    defaults:       { _controller: LichessBundle:Player:claimDraw }
    requirements:   { id: "[\w\-]{12}" }
lichess_locale:
    pattern:        /locale/:locale
    defaults:       { _controller: LichessBundle:Main:locale }
lichess_toggle_sound:
    pattern:        /toggle-sound
    defaults:       { _controller: LichessBundle:Main:toggleSound }
lichess_translate:
    pattern:        /translate/:locale
    defaults:       { _controller: LichessBundle:Translation:index, locale: " " }
lichess_translate_list:
    pattern:        /translate_list
    defaults:       { _controller: LichessBundle:Translation:list }
lichess_pgn_viewer:
    pattern:        /analyse/:id/:color
    defaults:       { _controller: LichessBundle:Pgn:analyse, color: white }
    requirements:   { id: "[\w\-]{8}", color: (white|black) }
lichess_pgn_export:
    pattern:        /export/:id
    defaults:       { _controller: LichessBundle:Pgn:export }
    requirements:   { id: "[\w\-]{8}" }
lichess_nb_players:
    pattern:        /how-many-players-now
    defaults:       { _controller: LichessBundle:Main:howManyPlayersNow }
