lichess_sync:
    pattern:        /sync/:hash/:version
    defaults:       { _controller: LichessBundle:Player:sync }
    requirements:   { hash: "[\w]{10}", version: "\d+" }
lichess_move:
    pattern:        /move/:hash/:version
    defaults:       { _controller: LichessBundle:Player:move }
    requirements:   { hash: "[\w]{10}", version: "\d+" }
lichess_say:
    pattern:        /talk/:hash/:version
    defaults:       { _controller: LichessBundle:Player:say }
    requirements:   { hash: "[\w]{10}", version: "\d+" }
lichess_homepage:
    pattern:        /:color
    defaults:       { _controller: LichessBundle:Main:index, color: white }
    requirements:   { color: (white|black) }
lichess_game:
    pattern:        /:hash
    defaults:       { _controller: LichessBundle:Game:show }
    requirements:   { hash: "[\w]{6}" }
lichess_player:
    pattern:        /:hash
    defaults:       { _controller: LichessBundle:Player:show }
    requirements:   { hash: "[\w]{10}" }
lichess_invite_ai:
    pattern:        /ai/:hash
    defaults:       { _controller: LichessBundle:Player:inviteAi }
    requirements:   { hash: "[\w]{10}" }
lichess_resign:
    pattern:        /resign/:hash/:version
    defaults:       { _controller: LichessBundle:Player:resign }
    requirements:   { hash: "[\w]{10}", version: "\d+" }
lichess_table:
    pattern:        /table/:hash
    defaults:       { _controller: LichessBundle:Player:table }
    requirements:   { hash: "[\w]{10}" }
lichess_opponent:
    pattern:        /opponent/:hash
    defaults:       { _controller: LichessBundle:Player:opponent }
    requirements:   { hash: "[\w]{10}" }
lichess_play_with_anybody:
    pattern:        /anybody/:hash
    defaults:       { _controller: LichessBundle:Player:playWithAnybody }
    requirements:   { hash: "[\w]{10}" }
lichess_ai_level:
    pattern:        /level/:hash
    defaults:       { _controller: LichessBundle:Player:aiLevel }
    requirements:   { hash: "[\w]{10}" }
lichess_about:
    pattern:        /about
    defaults:       { _controller: LichessBundle:Main:about }
lichess_rematch:
    pattern:        /rematch/:hash
    defaults:       { _controller: LichessBundle:Player:rematch }
    requirements:   { hash: "[\w]{10}" }
lichess_force_resignation:
    pattern:        /force_resign/:hash
    defaults:       { _controller: LichessBundle:Player:forceResign }
    requirements:   { hash: "[\w]{10}" }
